name: Deploy FastAPI to Vercel with Docker on Pull Request

on:
  pull_request:
    branches:
      - main  

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      # change directory to fastapi-backend before building the Docker image
      - name: Change to fastapi-backend directory
        run: cd fastapi-backend

      # build Docker image inside the fastapi-backend folder
      - name: Build Docker image
        run: |
          cd fastapi-backend  
          docker build -t fastapi-app .

      # deploy Docker image to Vercel
      - name: Push Docker image to Vercel
        uses: amondnet/vercel-action@v25
        id: vercel-deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}

      - name: Get preview URL
        run: |
          echo "Preview URL: ${{ steps.vercel-deploy.outputs.preview-url }}"
